<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1491287788675" stop="1491287788703">
	<name>angularjs homepage todo list</name>
	<title>angularjs homepage todo list</title>
	<test-cases>
		<test-case start="1491287788675" stop="1491287788703" status="failed">
			<name>should add a todo</name>
			<title>should add a todo</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
			</attachments>
			<failure>
				<message>Failed: get is not defined</message>
				<stack-trace>ReferenceError: get is not defined
    at Object.&lt;anonymous&gt; (F:\Protractor\New\binding.js:4:9)
    at C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:110:25
    at new ManagedPromise (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1067:7)
    at ControlFlow.promise (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2396:12)
    at schedulerExecute (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2860:25)
    at C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: Run it(&quot;should add a todo&quot;) in control flow
    at Object.&lt;anonymous&gt; (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attemptAsync (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1980:24)
    at QueueRunner.run (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1935:9)
    at QueueRunner.execute (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1923:10)
    at Spec.queueRunnerFactory (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:714:35)
    at Spec.execute (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:371:10)
    at Object.fn (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2579:37)
    at attemptAsync (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1980:24)
    at QueueRunner.run (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1935:9)
    at QueueRunner.execute (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1923:10)
From asynchronous test: 
Error
    at Suite.&lt;anonymous&gt; (F:\Protractor\New\binding.js:3:5)
    at addSpecsToSuite (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:867:25)
    at Env.describe (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:836:7)
    at describe (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:3576:18)
    at Object.&lt;anonymous&gt; (F:\Protractor\New\binding.js:1:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>